name: CloudDeployment

# on commit push, run job
on:
    push:
      branches: [ "main" ]
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
    - uses: 'actions/checkout@v4'
 
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/544071387477/locations/global/workloadIdentityPools/my-github-pool/providers/my-github-provider'
        service_account: 'githubactions-cloudfunctions@mms-clp-playground2402-a-x11e.iam.gserviceaccount.com'
 
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      with:
        name: 'Calculator-API'
        runtime: 'go121'
        entrypoint: 'CalculatorFunction'
        region: 'europe-west1'
        source_dir: ./../src
        project_id: ${{ secrets.GCP_PROJECT_ID }}
